### ISSUE TITLE
only add fkms overlay if necessary

### ISSUE THREAD

**Issue by cshields** [stream-pi/scripts#5]
I have less than an hour's experience with stream-pi so I'm filing this as an issue for consideration rather than jumping in with any kind of PR. Great project, and lots of potential!!

In my case I was trying this on a pi with a [hyperpixel4](https://shop.pimoroni.com/products/hyperpixel-4?variant=12569485443155) installed. I started with a fresh raspios install, then added the hyperpixel4 configuration, then installed stream-pi.

I had to go back and make one change for this to work and it comes back to [this line](https://github.com/stream-pi/scripts/blob/98f3e88e7f52b7947d7a25fd0cb1b916c9accf63/client-install-raspberry-pi.sh#L198
) in the install script.. in my case the hyperpixel install had already replaced the kms overlay with `dtoverlay=hyperpixel4`, but this is a scenario not caught in the stream-pi script, which then adds the `dtoverlay=vc4-fkms-v3d` line which does not work in this case.

Could of knee-jerk thoughts..  One would be to exclude the add if the hyperpixel4 dtoverlay exists, but there may be other edge cases like this out there. Another idea may be to only add the fake kms overlay if the vc4-kms-v3d overlay was previously set.

Cool app, keep up the good work!

**Comment by rnayabed** [comment]
The KMS driver is used only when Stream-Pi is used in Console mode leveraging hardware acceleration. KMS driver is not at all required if Stream-Pi runs on top of X.

We can ask the user in the script whether they want to turn on KMS driver before it does by itself. And give a brief warning that if its not turned on, stream-pi will not work in console mode and cant use hardware acceleration. Also mention that using kms may interfere with certain devices like hyperpixel that does not support using KMS driver at all.

Thanks for appreciating and liking Stream-Pi. Have a nice day, and if you find this app useful, please do consider donating or atleast star the repositories. Really motivates us a lot :)

**Comment by rnayabed** [comment]
The script has been updated and a lot of additional options have been provided along with this prompt:

```
===================================
ATTENTION! PLEASE READ CAREFULLY!

Stream-Pi Client can run either in Console Mode or Desktop Mode.
It is recommended to use console mode as Stream-Pi Client can then leverage Hardware acceleration and offer a smooth experience.

Stream-Pi Client CANNOT run in console mode with the KMS Driver turned OFF.

To ensure maximum compatibility, Stream-Pi Client can also run in Desktop Mode in case KMS is not available/disabled.

However, certain screens like the HyperPixel for Raspberry Pi conflicts with the KMS driver.
Stream-Pi Client can still run on these screens using desktop mode.

Fortunately, most screens like the Official 7" Raspberry Pi Display, Waveshare screens (including clones) work well with KMS Driver.



You can later disable or enable the KMS driver using the "raspi-config" tool, or by modifying /boot/config.txt

Do you want to turn on the KMS Driver ? [Y/N]
```

In case if user wants to skip prompt, they can just use `-ky` (for yes) or `-kn` (for no) as argument and skip the prompt entirely.
